routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/**
 * Author Deepak
 * Customer Routes
 */
Route::resource('customers' , 'CustomerController');

Route::post('search' , 'CustomerController@search')->name('search');

Route::get('/customer/create', 'CustomerController@createCustomer')->name('customer.create');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'skill', 'cv', 'address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CustomerRegisterRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Config;
use Mockery\Exception;

class CustomerController extends Controller
{
    /**
     * Author Deepak Thakur
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('customer.index', ['users' => User::paginate(Config::get('app.pagination_limit'))]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerRegisterRequest $request, User $user)
    {
        try {
            DB::beginTransaction();
            if ($request->persist($user)) {
                DB::commit();
            }
            return redirect()->route('customers.index');
        } catch (Exception $e) {
            DB::rollBack();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('customer.edit', ['user' => User::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CustomerRegisterRequest $request, User $customer)
    {
        try {
            DB::beginTransaction();
            if ($request->persist($customer)) {
                DB::commit();
            }
            return redirect()->route('customers.index');

        } catch (Exception $e) {
            DB::rollBack();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $customer)
    {
        try {
            DB::beginTransaction();
            if ($customer->delete()) {
                DB::commit();
            }
            return redirect()->route('customers.index')->with('message', 'User Successfully Deleted');
        } catch (Exception $e) {
            DB::rollBack();
        }
    }

    public function createCustomer()
    {
        return view('customer.create');
    }

    /**
     * Author Deepak Thakur
     * @return mixed
     */
    public function search()
    {

        $this->User = new User();
        $data = request('name');
        if (request()->has('name') && request()->get('name') !== null) {
            $query = $this->User->newQuery()
                ->orderBy('last_name', 'Asc')
                ->orderBy('first_name', 'Asc');


            $query->whereRaw('LCASE(`first_name`) LIKE ?', ["%" . trim(strtolower($data)) . "%"])
                ->orWhereRaw('LCASE(`last_name`) LIKE ?', ["%" . trim(strtolower($data)) . "%"])
                ->orWhereRaw('LCASE(`skill`) LIKE ?', ["%" . trim(strtolower($data)) . "%"]);


            if (request()->get('pagination', "true") == "true") {
                $paginator = $query->paginate(
                    request()->get('limit', \Config::get('app.pagination_limit')),
                    ['*'],
                    'page',
                    request()->get('page', 1)
                );

                return view('customer.index-search', ['users' => $paginator]);

            }

        }
        return view('customer.index-search', [User::paginate(Config::get('app.pagination_limit'))]);

    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register Customer') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('customers.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="firstName" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="lastName" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}"  autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="skill" class="col-md-4 col-form-label text-md-right">{{ __('Skill') }}</label>

                            <div class="col-md-6">
                                <input id="skill" type="text" class="form-control @error('skill') is-invalid @enderror" name="skill" value="{{ old('skill') }}" required autocomplete="skill" autofocus>

                                @error('skill')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>
                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ old('address') }}" required autocomplete="address" autofocus>

                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="cv" class="col-md-4 col-form-label text-md-right">{{ __('cv') }}</label>

                            <div class="col-md-6">
                                <input id="cv" type="file" class="form-control @error('cv') is-invalid @enderror" name="cv" value="{{ old('cv') }}" required autocomplete="cv" autofocus>

                                @error('cv')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Customer') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route( 'customers.update', $user->id ) }}" enctype="multipart/form-data">
                        @csrf
                          @method('PATCH')
                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="firstName" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') ? old('first_name') : $user->first_name }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="lastName" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') ? old('last_name') : $user->last_name }}"  autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="skill" class="col-md-4 col-form-label text-md-right">{{ __('Skill') }}</label>

                            <div class="col-md-6">
                                <input id="skill" type="text" class="form-control @error('skill') is-invalid @enderror" name="skill" value="{{ old('skill') ? old('skill') : $user->skill  }}" required autocomplete="skill" autofocus>

                                @error('skill')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>
                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ old('address') ? old('address') : $user->address }}" required autocomplete="address" autofocus>

                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="cv" class="col-md-4 col-form-label text-md-right">{{ __('cv') }}</label>

                            <div class="col-md-6">
                                <input id="cv" type="file" class="form-control @error('cv') is-invalid @enderror" name="cv" value="{{ old('cv') }}" required autocomplete="cv" autofocus>

                                @error('cv')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/index-search.blade.php
                            <tr>
                                <th>Sr No.</th>
                                <th>Name</th>
                                <th>Skill</th>
                                <th>Address</th>
                                <th>Action</th>
                            </tr>
                            @foreach( $users as $user )
                                <tr>
                                    <td>{{ (($users->currentPage() - 1 ) * $users->perPage() ) + $loop->iteration }}</td>
                                    <td>{{ $user->first_name .' '. $user->last_name }}</td>
                                    <td>{{ $user->skill }}</td>
                                    <td>{{ $user->address }}</td>
                                    <td>
                                        <a class="btn btn-primary"
                                           href="{{ route( 'customers.edit', $user->id ) }}">Edit</a>
                                        <a class="btn btn-primary btn-danger"
                                           href="{{ route( 'customers.destroy', $user->id ) }}" onclick="event.preventDefault();
                                                     document.getElementById( 'delete-user' ).submit();">Delete</a>
                                        <form id="delete-user"
                                              action="{{ route( 'customers.destroy', ['customer'=>$user->id] ) }}"
                                              method="POST" style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            @if(count($users) == 0)
                                <tr>
                                    <td>No Record Found</td>
                                </tr>
                            @endif

                        @if(count($users) > 0)
                            {{ $users->render() }}
                        @endif

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading mb-5"><span>Customer Listing</span>
                        <div class="btn-and serach">
                            <div class="search-field">
                                <form><input class="normal-search" type="text" value="" placeholder="Search.."> <input
                                            class="advance-search hide" type="text" placeholder="Advance  Search..">
                                    <span class="toglesearch">Advance Search</span> <span class="nrml-btn hide">Normal Search</span>
                                </form>
                            </div>

                            <a href="{{ route('customer.create') }}" class="btn btn-primary float-right">New
                                Customer</a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table id="laravel_datatable" class="table">
                            <tr>
                                <th>Sr No.</th>
                                <th>Name</th>
                                <th>Skill</th>
                                <th>Address</th>
                                <th>Action</th>
                            </tr>
                            @foreach( $users as $user )
                                <tr>
                                    <td>{{ (($users->currentPage() - 1 ) * $users->perPage() ) + $loop->iteration }}</td>
                                    <td>{{ $user->first_name .' '. $user->last_name }}</td>
                                    <td>{{ $user->skill }}</td>
                                    <td>{{ $user->address }}</td>
                                    <td>
                                        <a class="btn btn-primary"
                                           href="{{ route( 'customers.edit', $user->id ) }}">Edit</a>
                                        <a class="btn btn-primary btn-danger"
                                           href="{{ route( 'customers.destroy', $user->id ) }}" onclick="event.preventDefault();
                                                     document.getElementById( 'delete-user' ).submit();">Delete</a>
                                        <form id="delete-user"
                                              action="{{ route( 'customers.destroy', ['customer'=>$user->id] ) }}"
                                              method="POST" style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            @if(count($users) == 0)
                                <tr>
                                    <td>No Record Found</td>
                                </tr>
                            @endif
                        </table>
                            @if(count($users) > 0)
                                {{ $users->render() }}
                            @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    @include('js_helper.customer')
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/js_helper/customer.blade.php
<script>

    $(".toglesearch").click(function(){
        $(".advance-search").removeClass("hide");
        $(".normal-search").addClass("hide");
        $(".nrml-btn").removeClass("hide");
        $(this).addClass("hide");
    });
    $(".nrml-btn").click(function(){

        $(".advance-search").addClass("hide");
        $(".normal-search").removeClass("hide");
        $(".nrml-btn").addClass("hide");
        $(".toglesearch").removeClass("hide");
    });


        {{--$('#laravel_datatable').DataTable({--}}
            {{--processing: true,--}}
            {{--serverSide: true,--}}
            {{--ajax: "{{ route('customers.index') }}",--}}
            {{--columns: [--}}
                {{--{ },--}}
                {{--{ },--}}
                {{--{ },--}}
                {{--{}--}}
            {{--]--}}
        {{--});--}}

        $( ".normal-search" ).keyup(function() {
            let data = $(this).val();
            $.ajax({
                type:'POST',
                url:'/search',
                data:{
                    '_token':'<?php echo csrf_token() ?>',
                    name:data
                },
                success:function(data) {
                    $('#laravel_datatable').html('');
                    $('#laravel_datatable').append(data);
                }
            });
        });

</script>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
{{--    <script src="{{ asset('js/app.js') }}" defer></script>--}}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>



    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>--}}
{{--                            </li>--}}
{{--                            @if (Route::has('register'))--}}
{{--                                <li class="nav-item">--}}
{{--                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
{{--                                </li>--}}
{{--                            @endif--}}
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
            <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

            @yield('script')
        </main>
    </div>
</body>
</html>